### ISSUE TITLE
chore(models): create models for frequently used objects

### ISSUE THREAD

**Issue by abhigyantrips** [CodeX-MIT-BLR/NoticeBoard#14]
Models help us validate the information received from the API, persist data in functions and easily convert incoming data into usable instances. Some of these include:

1. Student
2. Club
3. Notice (Event)
4. Notice (Announcement)

As we are still in the process of confirming the `notice` model on the API, we should go ahead with a sample model to lay down the foundation.

```ts
interface Notice {
  String name;                     // Name of event
  String tagline;                  // Used in Notice card and notification
  String description;              // Upto 512 characters, supports markdown
  DateTime dateTime;               // Date and Time of the venue
  String type = "event" | "announcement";
  ...
}
``` 

**Refer:**

_API - https://github.com/Alphaspiderman/mitblr-club-api/tree/master/mitblr_club_api/models_
_Logistics App - https://github.com/mitblr-club/logistics/tree/main/lib/src/events/models_

Feel free to share better examples of model classes here; this was my jugaad solution while trying to parse a JSON.

**Comment by Chandan-CV** [comment]
@abhigyantrips, @scenario7 must have given the api requirements by now. converting the Json API response is super simple and will be done as soon as the api endpoint is ready to make it easier...
just paste your api response to [quicktype.io](url) to get the dart model of the same and functions to convert from json to dart class and vice versa... 

If we don't wanna keep this step as the last one, I'll prolly go through the api spec sheet and create the classes. What do you think?

**Comment by abhigyantrips** [comment]
Tried this out with `freezed_annotation` in #19, which auto-generates all relevant funtions and types (saves a lot of time). It also utilizes `json_serializable` and `build_runner`'s watch function for the same. Will explore more with the same library in an upcoming PR.
