### ISSUE TITLE
Need for functionality to add links onto the App

### ISSUE THREAD

**Issue by Rochak-Saini** [CodeX-MIT-BLR/NoticeBoard#8]
The following features are needed:
- Ability to add clickable links in the event listing title, sub-title, contents and image.
- A button on the event listing tile

@Chandan-CV @scenario7 Please look into this

**Comment by Rochak-Saini** [comment]
@Chandan-CV @scenario7 updates on this?

**Comment by abhigyantrips** [comment]
Closing this as 'stale'.
